# Website Basic Information
baseURL = "https://blogde.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm Blog"
languageCode = "de-de"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Startseite"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Beiträge"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # 首页显示最新 5 篇文章
mainSections = ["posts"]  # Home 页面只显示 type 为 "posts" 的文章